spring.application.name=flex-identity
spring.config.import=optional:configserver:http://localhost:9090

spring.r2dbc.url=r2dbc:mysql://localhost:3306/flexibiz_identity_service
spring.r2dbc.username=root
spring.r2dbc.password=
